# Generated by Django 3.2.23 on 2023-12-22 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbs',
            field=models.ManyToManyField(blank=True, default=None, related_name='thumbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
